version: '3.8'

services:
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: yt-downloader-api
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - ALLOW_ALL=true
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY:-}
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX_REQUESTS=100
      - LOG_LEVEL=info
    volumes:
      - ./downloads:/app/downloads
    networks:
      - yt-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on: []

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    container_name: yt-downloader-web
    restart: unless-stopped
    environment:
      - VITE_API_BASE=https://yt.local
    networks:
      - yt-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - api

  nginx:
    image: nginx:alpine
    container_name: yt-downloader-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./infra/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./infra/certs:/etc/nginx/certs:ro
      - nginx-cache:/var/cache/nginx
      - nginx-logs:/var/log/nginx
    networks:
      - yt-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    depends_on:
      - api
      - web

volumes:
  nginx-cache:
    driver: local
  nginx-logs:
    driver: local

networks:
  yt-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
